INSERT INTO doctors (nombre, apellidos, especialidad) VALUES
('Luis', 'Martín', 'Cardiología'),
('Alberto', 'Pérez', 'Dermatología'),
('Marta', 'Moreno', 'Ginecología'),
('Eva', 'Hidalgo', 'Pediatría'),
('Ricardo', 'Cruz', 'Neumología'),
('Sergio', 'González', 'Psiquiatría'),
('Julia', 'Romero', 'Oftalmología'),
('Miguel', 'Herrera', 'Neurología'),
('Patricia', 'Torres', 'Endocrinología'),
('Raúl', 'Mendoza', 'Reumatología'),
('Carmen', 'Vargas', 'Traumatología'),
('Ignacio', 'Guerrero', 'Urología'),
('Susana', 'León', 'Oncología'),
('Manuel', 'Santos', 'Medicina Interna'),
('Beatriz', 'Esteban', 'Otorrinolaringología'),
('Daniel', 'Pardo', 'Geriatría'),
('Alicia', 'Suárez', 'Hematología'),
('Hugo', 'Pascual', 'Nefrología'),
('Sara', 'Blanco', 'Cirugía General'),
('Óscar', 'Márquez', 'Anestesiología');
