INSERT INTO doctors (nombre, apellidos, especialidad, role, email, password) VALUES
('Luis', 'Martín', 'Cardiología', 'Doctor', 'luis.martin@clinic.com', 'password123'),
('Alberto', 'Pérez', 'Dermatología', 'Doctor', 'alberto.perez@clinic.com', 'password123'),
('Marta', 'Moreno', 'Ginecología', 'Doctor', 'marta.moreno@clinic.com', 'password123'),
('Eva', 'Hidalgo', 'Pediatría', 'Doctor', 'eva.hidalgo@clinic.com', 'password123'),
('Ricardo', 'Cruz', 'Neumología', 'Doctor', 'ricardo.cruz@clinic.com', 'password123'),
('Sergio', 'González', 'Psiquiatría', 'Doctor', 'sergio.gonzalez@clinic.com', 'password123'),
('Julia', 'Romero', 'Oftalmología', 'Doctor', 'julia.romero@clinic.com', 'password123'),
('Miguel', 'Herrera', 'Neurología', 'Doctor', 'miguel.herrera@clinic.com', 'password123'),
('Patricia', 'Torres', 'Endocrinología', 'Doctor', 'patricia.torres@clinic.com', 'password123'),
('Raúl', 'Mendoza', 'Reumatología', 'Doctor', 'raul.mendoza@clinic.com', 'password123'),
('Carmen', 'Vargas', 'Traumatología', 'Doctor', 'carmen.vargas@clinic.com', 'password123'),
('Ignacio', 'Guerrero', 'Urología', 'Doctor', 'ignacio.guerrero@clinic.com', 'password123'),
('Susana', 'León', 'Oncología', 'Doctor', 'susana.leon@clinic.com', 'password123'),
('Manuel', 'Santos', 'Medicina Interna', 'Doctor', 'manuel.santos@clinic.com', 'password123'),
('Beatriz', 'Esteban', 'Otorrinolaringología', 'Doctor', 'beatriz.esteban@clinic.com', 'password123'),
('Daniel', 'Pardo', 'Geriatría', 'Doctor', 'daniel.pardo@clinic.com', 'password123'),
('Alicia', 'Suárez', 'Hematología', 'Doctor', 'alicia.suarez@clinic.com', 'password123'),
('Hugo', 'Pascual', 'Nefrología', 'Doctor', 'hugo.pascual@clinic.com', 'password123'),
('Sara', 'Blanco', 'Cirugía General', 'Doctor', 'sara.blanco@clinic.com', 'password123'),
('Óscar', 'Márquez', 'Anestesiología', 'Doctor', 'oscar.marquez@clinic.com', 'password123');

