INSERT INTO medications (nombre, efectoSecundario, tipo) VALUES
('Ibuprofeno', 'Náuseas, mareos', 'Antiinflamatorio'),
('Amoxicilina', 'Reacciones alérgicas', 'Antibiótico'),
('Loratadina', 'Somnolencia', 'Antihistamínico'),
('Paracetamol', 'Irritación gástrica', 'Analgésico'),
('Metformina', 'Dolor abdominal', 'Antidiabético'),
('Enalapril', 'Tos seca', 'Antihipertensivo'),
('Atorvastatina', 'Dolor muscular', 'Hipolipemiante'),
('Omeprazol', 'Dolor de cabeza', 'Antiácido'),
('Aspirina', 'Sangrado', 'Analgésico'),
('Ciprofloxacino', 'Molestias digestivas', 'Antibiótico'),
('Furosemida', 'Calambres', 'Diurético'),
('Levotiroxina', 'Pérdida de peso', 'Hormona tiroidea'),
('Diazepam', 'Dependencia', 'Ansiolítico'),
('Diclofenaco', 'Malestar estomacal', 'Antiinflamatorio'),
('Clorhidrato de Metoclopramida', 'Fatiga', 'Antiemético'),
('Salbutamol', 'Palpitaciones', 'Broncodilatador'),
('Insulina', 'Hipoglucemia', 'Antidiabético'),
('Azitromicina', 'Dolor abdominal', 'Antibiótico'),
('Carbamazepina', 'Somnolencia', 'Anticonvulsivo'),
('Losartán', 'Mareos', 'Antihipertensivo');
