INSERT INTO prescriptions (pacienteID, nombre, descripcions) VALUES
(1, 'Tratamiento Gripe', 'Tomar un comprimido de Ibuprofeno cada 8 horas por 5 días.'),
(2, 'Dolor de Cabeza', 'Paracetamol cada 6 horas según sea necesario para el dolor.'),
(3, 'Antialérgico', 'Tomar un comprimido de Loratadina una vez al día por 10 días.'),
(4, 'Tratamiento para la tos', 'Jarabe para la tos, 10 ml cada 4 horas hasta mejorar.'),
(5, 'Infección Urinaria', 'Amoxicilina 500 mg cada 8 horas durante 7 días.'),
(6, 'Dolor Muscular', 'Ibuprofeno 400 mg cada 6 horas por 3 días.'),
(7, 'Tratamiento Asma', 'Inhalador cada 4 horas según sea necesario.'),
(8, 'Resfriado Común', 'Vitamina C y Zinc una vez al día por 2 semanas.'),
(9, 'Control Colesterol', 'Atorvastatina 20 mg cada noche antes de dormir.'),
(10, 'Ansiedad', 'Tomar Diazepam según indicaciones del médico.'),
(11, 'Antibiótico', 'Ciprofloxacino cada 12 horas por 7 días.'),
(12, 'Presión Alta', 'Losartán 50 mg cada mañana.'),
(13, 'Diabetes', 'Insulina subcutánea según la dosis indicada.'),
(14, 'Alergia Primaveral', 'Loratadina una vez al día mientras persistan síntomas.'),
(15, 'Tratamiento de Migraña', 'Sumatriptán al inicio del dolor.'),
(16, 'Tratamiento de Hongos', 'Aplicar crema antifúngica dos veces al día.'),
(17, 'Infección Estomacal', 'Metronidazol cada 8 horas por 5 días.'),
(18, 'Suplemento Vitamínico', 'Complejo B una vez al día con las comidas.'),
(19, 'Trastorno del Sueño', 'Melatonina 3 mg antes de dormir.'),
(20, 'Terapia Hormonal', 'Estrógenos según pauta médica, una vez al día.');
